### PR TITLE
Design adaptations

### PR DESCRIPTION
**Pull request by fippu82**
@incpi I have changed the position units from px to rem. But I can't figure out how to change the default color and change the black theme color to something else. Can you please help with this or point me to the right direction?

### CODE REVIEW

**Comment by DevGregor** [comment]
@fippu82 
We set the background color here:
image
We need to make sure to change the text color of all the child nodes to something bright since SAP has made the header bar inverted in the newest UI. We also don't have to worry about "the old UI" if we change the text color because it is already something bright.

Old UI (still used in CF currently) -> already has bright text color by SAP
image

New UI (only in Neo atm) -> has dark text color by SAP
image

**Comment by incpi** [comment]
Hi @fippu82 /@DevGregor ,

There is property cpi custom color in css just change default blue to #fff.

for user selected color you might need to tweak logic for auto color adjusters to restrict by dark colors. Right now it is restricted by bright colors.

Might need to remove black option at all.

**Comment by fippu82** [comment]
Thanks for your inputs. Yes, I tried to change the logic in popup.js (where the color selector is) but it somehow had no impact. Will look into it again later.

**Comment by DevGregor** [comment]
> Thanks for your inputs. Yes, I tried to change the logic in popup.js (where the color selector is) but it somehow had no impact. Will look into it again later.

@fippu82 / @incpi 
But take a look at line 174-175. This sets that property "--cpi-custom-color" so I think this overwrites it. The color is defined in the variable hostData:
image

**Comment by incpi** [comment]
Hi,

You are right, It does overwrite...

But no need to change it, just replace the 2nd snapshot value with #ffffff

**Comment by DevGregor** [comment]
> Hi,
> 
> You are right, It does overwrite...
> 
> But no need to change it, just replace the 2nd snapshot value with #ffffff
> 
> It's not easy to just flip the value but it needs a bit more attention. It has a lot of impact here and there

I don't think this will work for 2 reasons:
- If we change it to white then in the Old UI it will be an issue, which means in CF it's going to be all white with white text.
- We are checking the storage and if there is a stored value we take it and overwrite hostData with it.

Functions are executed in this order:
image
getHostData function checks the storage and overwrites hostData if there is something stored already:
image
Notice that within getHostData we also call setData and if you go down the line it will eventually set the header bar color with the function setHeaderColor

**Comment by fippu82** [comment]
Hi guys, thank you @incpi for the changes you already made in my fork. However, I'm not sure what we are actually trying to achieve. In my opinion, we have only these two rather small problems: 

1. If somebody has the dark blue or black color activated today -> when their layout changes to the new SAP UI, they can hardly read the icons (and the title "Cloud Integration") on the header.

The easy solution for the user would be to change the theme to another color. From our side: we have removed black from the color selector.

2. The "Reset Color" button defaults to dark blue (old SAP UI theme) -> here we just set it to something that works on both SAP UI themes for now, e.g. (light) blue. Later, when all tenants are moved to the new UI theme, we can set it to white which is the default header color of the new UI. 

That's a pragmatic and simple approach. 

Let me know if I'm missing something.  I create a draft PR into the Dev branch now.

**Comment by incpi** [comment]
Hi @fippu82 ,

My objective ,
At the time we are done with changes, it's most probably sap will release it in the CF horizon theme.

So,

- [x] 2 objectives are achieved what you mentioned.
- [ ] issue when the user selects dark color in popup text goes missing if color matches same as  initial issue. Need contrast
- [ ] header of popup and sap header are different. Not always matching,

IMO, create a css property that changes dynamically instead of doing a lot of changing the code in html js etc.

**Comment by DevGregor** [comment]
New UI seems to be rolled out in CF too. @fippu82 / @incpi

**Comment by dbeck121** [comment]
Perfect! I will care for next release

@fippu82 could you add changes to changelog?

**Pull request merged**
