### PR TITLE
new Version 3.7.1

### PR DESCRIPTION
**Pull request by dbeck121**

### CODE REVIEW

**Comment by dbeck121** [comment]
Version 3.17.1 with @fippu82s changes.

@dbeck121 @fippu82  @DevGregor @Incpi  any veto? If not, please approve one of you.

**Comment by Incpi** [comment]
Hello
 - Small thing but Firefox manifest need to update version

**Comment by dbeck121** [comment]
> Hi, If it goes ignored, A minor issue,
> 
> * firefox's manifest version has to be updated.
> * Clean bin folder (Workflow not cleaning (1st time only hope so.))
> 
> Thanks

you mean to 3? Yes... and right. bin folder needs to be cleaned.

**Comment by Incpi** [comment]
No version number. 3.17.0 to 3.17.1

Firefox not support v3 😅

**Pull request closed without merging**
