### PR TITLE
Release v3.17.0

### PR DESCRIPTION
**Pull request by dbeck121**

### CODE REVIEW

**Comment by dbeck121** [comment]
@fippu82 @Incpi @DevGregor: Could one of you please final check if there is not a bigger problem with 3.17.0?

**Comment by Incpi** [comment]
Hello @dbeck121 ,
- bin folder needed to be cleaned (3.16.0)

**Comment by fippu82** [comment]
@dbeck121  I pulled it and will be testing it a bit tomorrow.

**Review by fippu82 — APPROVED** [review]
I haven't found any bugs so far.

**Comment by dbeck121** [comment]
> Hello @dbeck121 ,
> 
> * bin folder needed to be cleaned (3.16.0).
> * trace not work (CPI version :6.58.27) if runtimeLocationId (only pass if defined) in my case it's not used.

Hey,

I pulled and created the zips manual. Should be online in all stores. But @Incpi: you are right. I need to delete it for next time.

**Comment by fippu82** [comment]
Strange, I haven't noticed this issue when testing. I might have forgot to reload the extension... Since we don't have auto-reload anymore, I haven't worked on this extension much so I wasn't used to it. Sorry about that! I have created PR https://github.com/dbeck121/CPI-Helper-Chrome-Extension/pull/241 that hopefully fixes the issue with the trace!

**Comment by fippu82** [comment]
I double checked and it seems I didn't catch the error because it only applies to CPI tenants with an active Edge Cell. All others works fine. My patch fixes the issue also for Edge Cell tenants.

**Pull request merged**
