### PR TITLE
WHINT Interface Documentation Plugin - Update v1.2

### PR DESCRIPTION
**Pull request by owais1412**
Hi Dominic,

We've released a new version of our plugin, added 2 more options in the settings and updated the plugin ID to `whint`.
Hope you can it include it in the next version of the CPI Helper.

Thanks,
Syed Owais

### CODE REVIEW

**Comment by dbeck121** [comment]
@owais1412 looks good and I can pull but you need to be sure to change id. This means the plugin will be in default state for all installations. 

Are you ok with this? otherwise you should keep the old name.

**Comment by owais1412** [comment]
@dbeck121 What does it mean that plugin will be default state for all installations?
The ID change was done by @jmailaender  and I think she can help up here.

**Comment by fippu82** [comment]
> @dbeck121 What does it mean that plugin will be default state for all installations? The ID change was done by @jmailaender and I think she can help up here.

I believe it is like a factory reset for this plug-in. User's configuration will be lost.

**Comment by dbeck121** [comment]
> @dbeck121 What does it mean that plugin will be default state for all installations? The ID change was done by @jmailaender and I think she can help up here.

Like @fippu82 said, it is a factory reset for the plugin settings. If you stay with WHINT_IFD, everything is fine and people keep their settings. If you do not need the settings of your plugin, this is fine.

**Review by dbeck121 — APPROVED** [review]

**Pull request merged**
