### PR TITLE
Timeline Plugin

### PR DESCRIPTION
**Pull request by DevGregor**
This plugin displays the timeline of a message. It adds a message sidebar button that opens a popup when clicked upon. (no trace needed)

The target of this Plugin is to help make a quick and easy overview and access of each step of a message
	e.g. especially when ProcessDirect is used you can view what artifacts were triggered by that message and in what order

If the message sidebar button (hourglass-Emoji) is clicked, the following steps are executed:
1. The message guid is used as filter to get the correlation id of that message that was clicked via MessagProcessingLogs API
2. The correlation id is used to filter out every connected artifact that has that correlation id and sorts them by LogStart via MessagProcessingLogs API
3. The received data is used to create an HTML table that contains: (a style tag is added as well but used are custom ids and classes)
	- Nr.
	- Integration Flow Name (also conatining a link to that artifact -> opens new tab)
	- Integration Package (also conatining a link to that package -> opens new tab)
	- Status
	- Start Date
	- Start Time
4. Load popup with the created table using the .popup(content, title) function provided by pluginHelper

I tried to display the timeline as tree but it seemed impossible (for now) for the following reasons:
- SAP doesn't provied distinguishable ids when splitters are used
- Timestamps can't be used since parallel processing in splitters is possible and not all timestamps are correct
	- I observed that at least if ProcessDirects are being used a

Here is a preview of the message sidebar and the popup:
image
image

### CODE REVIEW

**Comment by DevGregor** [comment]
Here is a preview of how it looks
Message Sidebar Button:
image

Popup:
image

**Review by incpi — COMMENTED** [review]
I like your thought for this plugin but there are few suggestions,

- Can we have status based raw colors?
- Instead of using custom table, can we use something like,
https://fomantic-ui.com/collections/table.html#colored-and-marked.

FYI, we can mark raw color as =>error=red, completed = green, active=yellow, etc.

**Comment by DevGregor** [comment]
> I like your thought for this plugin but there are few suggestions,
> 
> * Can we have status based raw colors?
> * Instead of using custom table, can we use something like,
>   https://fomantic-ui.com/collections/table.html#colored-and-marked. (supported by default in this extension)
> 
> FYI, we can mark raw color as =>error=red, completed = green, active=yellow, etc.

I will take a look into this and adjust it.

**Comment by DevGregor** [comment]
> I like your thought for this plugin but there are few suggestions,
> 
> * Can we have status based raw colors?
> * Instead of using custom table, can we use something like,
>   https://fomantic-ui.com/collections/table.html#colored-and-marked. (supported by default in this extension)
> 
> FYI, we can mark raw color as =>error=red, completed = green, active=yellow, etc.

Here you go
image
image

For default I went with orange since yellow is my active color. I also tried using some icons but it never displayed anything.

**Comment by DevGregor** [comment]
Can we add this information about styling to the plugins ReadMe file? I was following that files instructions and that's why I used a custom styling initally.

**Comment by dbeck121** [comment]
@DevGregor Thank you very much for the contribution. That is a really nice idea!

I will test it and come back to you. May I add your name and Link to your Githib profile in the next release?

**Comment by DevGregor** [comment]
> @DevGregor Thank you very much for the contribution. That is a really nice idea!
> 
> I will test it and come back to you. May I add your name and Link to your Githib profile in the next release?

Yes, of course! 😄

**Pull request merged**
