### PR TITLE
fix: remove background worker + performance improvements

### PR DESCRIPTION
**Pull request by dbeck121**
I removed the background worker so we could switch to manifest 3 in Firefox. 

The background worker catched the XCsrf token for trace.

Maybe someone can test (trace gets activated)

--
edit: 

I also improved performance a bit: observer are more specific, buildbuttonbar loads later

edit2:

I added a better Cache for API calls. Now you can specify a time to live of the cache in makeCallPromise. Before it was just a boolean (which is still possible and has a default ttl of 10 minutes). So cache does not get filled to much.

@fippu82 for each refresh of the message sidebar there were 3 calls to SAP. I added 120 seconds cache to them because I guess there are not that much changes. Please check if that is ok.

edit3: 
I improved manifest so it might survive login. 
Can be tested now and is my suggestion for 3.18.0 if nobody has other pr.

### CODE REVIEW

**Review by Incpi — APPROVED** [review]
Trace working in CF for me.

**Comment by dbeck121** [comment]
> Trace working in CF for me (Firefox & Chrome).

ah nice. I still struggle a bit to test in firefox.

**Comment by dbeck121** [comment]
> Trace working in CF for me (Firefox & Chrome).

@Incpi I added other commits. I did not open another branch because they were connected to this topic. Could you maxbe retest?

**Review by Incpi — APPROVED** [review]
Working Good in both. General Use.

**Pull request merged**
