### PR TITLE
Ui Table Upgrade modals

### PR DESCRIPTION
**Pull request by incpi**
Hi everyone,
I've updated the UI to make it more consistent across the extension. For example, the logs and trace info pages now have the same look and feel. It's not a big change, but I hope it improves your experience.
Here's a preview as always:
image

I'm happy to say that I've finished all the UI changes I planned to do. It was a pleasure working with you. Thank you for all your feedback and support.

### CODE REVIEW

**Comment by dbeck121** [comment]
Nice :) Thanks!

**Comment by fippu82** [comment]
> I'm happy to say that I've finished all the UI changes I planned to do. It was a pleasure working with you. Thank you for all your feedback and support.

@incpi Thank you Omkar for your awesome UI contributions! Really helped advancing CPI Helper by a lot.

**Comment by incpi** [comment]
> Nice :) Thanks!

@dbeck121 ,
Just 1 request I have, Will you upgrade FUI 2.9 (Released 1 year ago) to next stable release (^2.9.1).

**Comment by dbeck121** [comment]
@incpi I can put it on my to-do list. Unfortunately it is not super easy as there are some things that needs to be changed in the library. Would 2.9.1 help you in some way?

**Comment by incpi** [comment]
Yes, I used it in a place to avoid large unnecessary code. Technically it's working but it's different visually.

It's better to have it. Currently they released 2.9.3 stable FYI.

**Pull request merged**
