### PR TITLE
Rewrite-UI-extension-page

### PR DESCRIPTION
**Pull request by incpi**
Hello dbeck121,

Once again, Greetings!!

[feature]
list view is not useful + height limit of 600px. too much flickered while long list scroll. too small clicking area....etc.
Long story short, i rewrite popup.html and js. with less overall height.

 While rewrite (fixed existing bugs in the UI).
**Preview as always**

image
image

Will you able to test "CPI Helper old version items" in last visited section because I am not able to. Thus, my commit ends here for this PR. Let me know if you encounter any issues.

Thank you in advance your help.
________
Thanks,
Omkar

### CODE REVIEW

**Comment by fippu82** [comment]
Hi Omkar, interesting new layout! I would try to align the menu entries better, so that the alignment doesn't look chaotic like now.  And regarding the colors: can we make Artifacts and Design both gray? 
But these are merely design point. Let's wait for @dbeck121's comment about the whole PR.

**Comment by incpi** [comment]
HI Fippu82,

Thank you for your feed back.
image
now it's not that chaotic if you compare with each row in monitoring page. Let me know your thoughts.

For color, I kept because it's most used buttons. will be highly clickable area and 2nd thing is both referencing to different page 1st to integration content and 2nd to design page. So, I can't keep same precedence to both of them. 

Will wait for review let's see.

Thanks,
Omkar

**Comment by fippu82** [comment]
@incpi  Thanks for your explanation. I see what you mean. Can we left align the labels? So that it looks like a table and not like four independent rows. That's what I mean with chaotic (they are now like floating and are not aligned).

And for the color: imo the blue should be darker, same as the default blue of the Helper (title bar). And the black for Artifacts could then be gray or dark gray. But black looks too negative :-)

**Comment by incpi** [comment]
Hello @dbeck121 @fippu82 , chaotic alignment (not working unless custom solution is written in CSS along with combability with UI). Updated with center alignment last commit. 

I will create 1 more PR. I like what you said for alignment, labels as left alignment. 
**Last visited** tab for this solution, it will increase height. Imo let user select what he wants to choose. Next will be last PR as per feedback you provided. Please mention me if you have any other feedback.

Sorry for making too many requests. 

Thank you.
Omkar

**Comment by fippu82** [comment]
Hi Omkar @incpi , 

The latest design looks awesome! Now I like the colors :-)  Thank you for changing it! 
And the "chaotic" buttons are now much better too like this. No need to change anymore, in my opinion. 

I will test the version 3.8 in the coming days and then it's up to @dbeck121 to decide about releasing it. 

Thank you, 
Philippe

**Pull request merged**
