### PR TITLE
Release 3 15 4

### PR DESCRIPTION
**Pull request by dbeck121**

### CODE REVIEW

**Comment by dbeck121** [comment]
@fippu82 @incpi @DevGregor 

I would like to release new version with a fix for number of entries in message sidebar. So please accept and I will release.

**Comment by fippu82** [comment]
@dbeck121  I'm testing it. Is it normal that the value in the settings is only saved when a refresh of the message bar occurs while the settings popup is open? If I change the value and immediately click away to close the popup, the value is not saved.

**Comment by incpi** [comment]
> @dbeck121 I'm testing it. Is it normal that the value in the settings is only saved when a refresh of the message bar occurs while the settings popup is open? If I change the value and immediately click away to close the popup, the value is not saved.

3sec timer to save

**Comment by fippu82** [comment]
@incpi Got it. Maybe we should mention at the top of the popup to wait for 3secs to save changes. What do you think?

**Comment by incpi** [comment]
> @incpi Got it. Maybe we should mention at the top of the popup to wait for 3secs to save changes. What do you think?

toast stating "Saved." better in top center or top right.

**Review by fippu82 — APPROVED** [review]

**Review by incpi — APPROVED** [review]
working

**Review by DevGregor — APPROVED** [review]

**Pull request merged**
