### PR TITLE
Fix  #207 no of last executions

### LINKED ISSUE #207: [Bug]: Fail when try to increase the last execution > 10
**Describe the bug**  
When attempting to increase the "No. of Last Execution" value beyond 10, the plugin does not display more than 10 executions. Reducing the number of last executions works as expected, but any attempt to set the value above 10 fails to show more than 10 executions.

**To Reproduce**  
1. Go to 'Settings'
2. Click on 'No. of Last Execution'
3. Increase the value to more than "10"
4. Observe that the list of executions does not reflect the increase beyond 10

**Expected behavior**  
The system should display the exact number of last executions as set in the "No. of Last Execution" field, even when the number is greater than 10.

**Version**  
v3.15.2

**Desktop (please complete the following information):**
- OS: Win11  
- Browser: Chrome  
- Version: 128.0.6613.138 (Official Build) (64-bit)

**Tenant type (please complete the following information):**
- Cloud Foundry / Multicloud

### PR DESCRIPTION
**Pull request by dbeck121**
@DevGregor @fippu82 @incpi 

This should fix #207. Please one of you test and approve!

### CODE REVIEW

**Review by incpi — APPROVED** [review]
Tested on CF
Working as expected.
Thanks

**Comment by DevGregor** [comment]
Tested on CF and Neo.
Didn't work for me. Only works for < 10 when I tried it.

**Comment by DevGregor** [comment]
Tested on CF and Neo. 
Works for me. (Had wrong branch first)

Using the arrows to increase only worked up to 20. after that I have to manually enter the higher numbers. If I use the arrows after manually entering a higher number than 20 it won't do anything unless you go lower, then it will instantly return to 20.

**Comment by dbeck121** [comment]
> Tested on CF and Neo. Works for me. (Had wrong branch first)
> 
> **Using the arrows to increase only worked up to 20. After that I have to manually enter the higher numbers.**
> 
> If I use the arrows after manually entering a higher number than 20, it won't do anything unless you go lower. If you do so, then it will instantly return to 20.
> 
> With arrows I mean these: image

Interesting... I do not see it as a blocker but let's keep it in mind.

**Comment by incpi** [comment]
> Tested on CF and Neo. 
> Works for me. (Had wrong branch first)
> 
> **Using the arrows to increase only worked up to 20. After that I have to manually enter the higher numbers.** 
> 
> If I use the arrows after manually entering a higher number than 20, it won't do anything unless you go lower. If you do so, then it will instantly return to 20.
> 
> With arrows I mean these:
> image
> 

@DevGregor , 


I designed that way as last 20 execution it will show, small screen like below fhd dont remember resolution like 768p or something, it will go out of window so it's restricted till 20.

Let me know if have this needs.

**Comment by DevGregor** [comment]
> > Tested on CF and Neo.
> > Works for me. (Had wrong branch first)
> > **Using the arrows to increase only worked up to 20. After that I have to manually enter the higher numbers.**
> > If I use the arrows after manually entering a higher number than 20, it won't do anything unless you go lower. If you do so, then it will instantly return to 20.
> > With arrows I mean these:
> > image
> 
> @DevGregor ,
> 
> I designed that way as last 20 execution it will show, small screen like below fhd dont remember resolution like 768p or something, it will go out of window so it's restricted till 20. Also v2 dominic has max 20 so, i maintain same. Let me know if have this needs.
> 
> Maxcount = 20 hostdata if i remember correctly.

20 is plenty for me but I just thought that it's weird because you can set it manually, so I don't really see the point in limiting it unless you do a general max size.

My screens are usually either 1080p or 1440p, so I can definetly use more than those 20 and acutally have them displayed.

**Pull request merged**
