### PR TITLE
Plugin Credential Helper

### PR DESCRIPTION
**Pull request by DevGregor**
**Description**
This plugin helps find existing aliases from Security Material and Key Store. It was wished for in https://github.com/dbeck121/CPI-Helper-Chrome-Extension/issues/151.

**Steps**
1. An Event Listener is added for the click events when CPI Helper is rendered and the plugin has been activated

2. If an input field for credentials is clicked it will get all the aliases from the Security Material and Key Store and add a new 
Event Listener for typing to that input field. The credential input field is distinguished by checking parts of the id.

3. Each letter that is typed will be compared to the list of aliases by using the include() function and toLowerCase(). E.g. typing 'test' will trigger 4 checks with the following strings: 't', 'te', 'tes' and 'test'

4. A dropdown will be added containing a div element for every matching alias. If there is no matching alias, a single item will be displayed, indicating that there are no matching aliases.

**Info**
I have tested this in both CF and Neo and it works for the following adapters with every auth type that you can choose and also every "sub" version (e.g. OData -> V2/V4 or SOAP -> SOAP 1.X/SAP RM):

- AMQP
- Ariba
- AS2
- AS4
- Elster
- Facebook
- FTP
- OData
- HTTP
- IDOC
- JDBC
- Kafka
- LDAP
- Mail
- MDI
- ODC
- SFTP
- SOAP
- SuccessFactors
- Twitter
- XI

### CODE REVIEW

**Comment by DevGregor** [comment]
If we want, we can add it as a sort of "Beta" Version. Any adjustments are welcome (especially adressing the issues mentioned).

**Comment by DevGregor** [comment]
@incpi 
Do you want to take a look at the issues here as well? I think your skills (especially in the frontend) would come in handy here! 😅

**Comment by incpi** [comment]
Hello @DevGregor ,

Sure, i will be happy to do it.

Could you please tell me which ( neo or cf ) tenant you used to develop this plugin ??

Thanks
Om

**Comment by incpi** [comment]
Hi @DevGregor / @dbeck121 ,

I am doing testing with default settings from the new trial account with basic capabilities of building integration scenarios and manage API only. 
==Where this Api is not available.==

Yes i do have mpl api but not security material apis.

I also deployed a few materials via ui as well.

Thanks,
Omkar

**Comment by DevGregor** [comment]
> > Hi @DevGregor / @dbeck121 ,
> > Sure, i will be grateful if i can contribute.
> > I am doing testing with default settings from the new trial account with basic capabilities of building integration scenarios and manage API only. **_Where this Api is not available_**
> > Yes i do have mpl api but not security material apis.
> > I also deployed a few materials via ui as well.
> > If it is restricted to only s-user. No analysis yet. Please let me know if you also facing it.
> > Thanks, Omkar
> 
> Getting the data should already be working quite right. I have also adjusted some frontend issues with the most recent commits. Now I'm trying to set the value in the input field but I've only gotten so far that you have to click the input field again once a value has been chosen and I don't really know why yet: image image After closing the adapter and reopening it is set back to what I typed initially (**if I don't click onto the input field again once**): image If you retype or choose a different value than it's resetted and we need to to the same over.

**Comment by DevGregor** [comment]
> Hi @DevGregor / @dbeck121 ,
> 
> Sure, i will be grateful if i can contribute.
> 
> I am doing testing with default settings from the new trial account with basic capabilities of building integration scenarios and manage API only. **_Where this user credentials Api is not available_**
> 
> Yes i do have mpl api but not security material apis.
> 
> I also deployed a few materials via ui as well.
> 
> If it is restricted to only s-user. No analysis yet. Please let me know if you also facing it.
> 
> Thanks, Omkar

Check the latest commits. I noticed that as well so I switched it to something I had before and it works for me on Neo and CF. Don't know about trial.

**Comment by DevGregor** [comment]
All major issues should be fixed now. Obviously it's not perfect but I think you can already use this in a good way. @incpi @dbeck121

**Comment by incpi** [comment]
@DevGregor Thanks,
I also switched that API URL for this reason. 
I was testing your plugin & when your plugin is enabled. downstream plugin are not working due to some info missing. Would you mind take a look at that issue?

**Comment by DevGregor** [comment]
> @DevGregor Thanks, I also switched that API URL for this reason. I was testing your plugin & when your plugin is enabled. downstream plugin are not working due to some info missing. Would you mind take a look at that issue? I didn't do why cuz its almost 3 am here.

What do you exactly mean with "downstream plugin". I have multiple plugins activated and all of them seem to be working.

**Comment by dbeck121** [comment]
Hey! 

Thank you both @DevGregor and @incpi working together. It is great to see. I love our community :-)

I am testing right now. I reverted last commit to reapply the plugin. I have no problem with other plugins. The box with credentials appears after typing in a credentials box. Looks super nice. 

Do you want the name of the credential to be put in the field after clicking?

**Comment by DevGregor** [comment]
> Hey!
> 
> Thank you both @DevGregor and @incpi working together. It is great to see. I love our community :-)
> 
> I am testing right now. I reverted last commit to reapply the plugin. I have no problem with other plugins. The box with credentials appears after typing in a credentials box. Looks super nice.
> 
> Do you want the name of the credential to be put in the field after clicking?

Hello :)

Yes, with the latest commits here it should be working so that it is set into the input field after selecting and also "saved" when you leave the adapter and reenter it.

**Comment by incpi** [comment]
@dbeck121 ,

Issue I mentioned was as follow,
- As this plugin render doesn't return any element. due to this below plugin sidebar content was not rendering, Plugin working but with No content rendered. 
- Cond: I have trace modifier and simple ref are active. in between i have this plugin.
- Behaviour: simple ref rendered, trace modifier data not rendered.
 
Fixed #167 as return made non mandatory.

**Comment by DevGregor** [comment]
> @dbeck121 ,
> 
> Issue I mentioned was as follow,
> 
> * As this plugin render doesn't return any element. due to this below plugin sidebar content was not rendering,following below Plugin working but with No content rendered.
> * Cond: I have trace modifier and simple ref are active. in between i have this plugin.
> * Behaviour: simple ref rendered, trace modifier data not rendered.
> 
> Fixed #167 as return made non mandatory.

Okay, thanks for the fix! @incpi 
Do we want to make a new "type" for plugins? I guess this plugin doesn't really make sense in the messageSidebarContent then but I didn't see a different way.

**Comment by fippu82** [comment]
@DevGregor I thought about that too yesterday and think we need an option for kind of "headless" plugins.

**Comment by DevGregor** [comment]
> @DevGregor I thought about that too yesterday and think we need an option for kind of "headless" plugins. Or is that already provided by @incpi's fix?

If I understood this correctly, then his fix means that it is **not mandatory to return a value** in the "onRender" function for messageSidebarContent.

**Comment by fippu82** [comment]
Which would fullfil the point. However, to make it more explicit, we could add a beoolean property like "headless" to the settings list. If set to true, no return value would be expected. But that's a detail.

**Comment by dbeck121** [comment]
I am a bit lost in your discussion. Just tell me when to pull :)

**Pull request merged**
