### PR TITLE
v3.15 Updates

### PR DESCRIPTION
**Pull request by incpi**
Hello Dominic / @Lunahri17,

#### Manifest Reversion for RAM Issue (#192)
- **Affected Capabilities:** Manage and Provide Integration Technology Guidance.
- **Issue:** Improper URL matching causing issues. Avoid unnecessary code injections. Prefer explicit URL declaration for better maintenance.
- **Fix:** Corrected incorrect and redundant manifest URLs for the CN server.

#### Color Mode Detection
- Automatically detects and applies dark mode by default.
 Dark Mode Applied

#### Improved Dark Mode Colors
- Adjusted colors for better readability in dark mode, especially for large integrations and zoomed-out views.
Improved Dark Mode Colors

#### Performance Stats Plugin
- Enhanced color scheme for dark mode.
Performance Stats Plugin

#### New Navigation Buttons
- Introduced buttons for seamless step navigation.
Navigation Buttons

#### Popup Positioning
- Popups are now state-aware for better positioning.

#### Latency Indicators
- Added loading indicators for latency between steps. Closable but suggest waiting.
Latency Indicator

#### Ace Editor Scrollbar Fix
- Fixed invisible scrollbar issue in dark theme. Updated with darker scrollbar to match.
image

#### Element Highlighting
- Active or last activated elements are now highlighted in teal. (Performance plugin: it won't show active element even it has teal color but different purpose.)
 Element Highlighting

#### Inline Trace Dimmer to blurred
- The dimmer effect is now blurred instead of black for faster popup display.
Inline Trace Dimmer

#### Toast Notification Support
- Toast notifications now support the dark theme.
Toast Notification

#### XML Declaration Preservation
- Ensured that XML declarations remain intact during code prettification.
XML Declaration

#### Download Option for Body Content
- Added a download option for body content with the proper file extension to reduce manual unzipping and copy-saving.
- New text-wrap option & better theme editor controls are added
Download Option
image

#### General UI Bug Fixes
- Various UI bugs have been addressed for a smoother experience.

#### What's new logs & UI Change
- No need to maintain manual work instead readme String as template. it will work
- UI is grouped so easier to follow

#### Backend Organization
- Improved backend organization by ensuring all appended elements are under a global element.
Backend Organization

Thank you

Best,  
Omkar

### CODE REVIEW

**Comment by Lunahri17** [comment]
yes, i don't think it needs to inject code on these apps.

**Comment by dbeck121** [comment]
Nice :-) Looks really good. Looking forward to test. Just ping me when I should merge. Right now I see draft state

**Comment by incpi** [comment]
@dbeck121, you can merge. let me know if any issue has found.
Thanks,
Omkar

**Comment by incpi** [comment]
@dbeck121 You can merge it. Do let me know if you face any issue.
Thanks

**Comment by dbeck121** [comment]
Great Work!

**Comment by fippu82** [comment]
Awesome, I love the Download Body function! Thanks so much for the contributions.

**Comment by shajipapn** [comment]
Hi,





It seems the trace is not getting activate for REST API flows since last week. In integration flows it's working fine.
Is it only for me or for everyone? Am i missing some config for REST API flows? 

Please suggest.

Regards
Jakku

**Pull request merged**
