### PR TITLE
Dark mode - For Test

### PR DESCRIPTION
**Pull request by incpi**
Hello All,

This will be the pull request for the dark mode feature. I would greatly appreciate it if you could try it out and provide your valuable feedback.

I am writing custom lib based on fomantic-Ui (works with this project only). 
Small preview:
image

- this will fix issue of cpi helper in dark mode.

Make a separate branch if needed.

Thank you.
Omkar

### CODE REVIEW

**Comment by dbeck121** [comment]
Hi,

sorry that you have to wait for so long. I will check this weekend!

**Comment by dbeck121** [comment]
@incpi 

can you give a bit background:
- Does it work standalone of in combination with your dark cpi plugin? It feels like the popup with settings work now in dark mode but for cpi itself, we need your plugin right?
- Together with your plugin, messagesidabar does not get dark

In general: works prety good so far.

**Comment by incpi** [comment]
Hello @dbeck121,

I'm altering it as I discovered it. Since I wrote my custom CSS (not perfect at all)

- Indeed, it is with the Dark CPI plugin.
- If someone wants to do a mismatch, such as bright with dark cpi helper, I have included a popup setting.
- with plugin, message sidebar does not get dark. Could you assist with the screenshot? My own is operational. with this branch.

If you need more info, let me know.
Thanks
Omkar

**Comment by incpi** [comment]
Indeed, @fippu82.

I appreciate you informing me of this. I completely forgot about it.

**Comment by fippu82** [comment]
@incpi  Thank you. But what do you mean by "kindly include this roughly every 15 lines."? I don't get you.

**Comment by incpi** [comment]
> @incpi  Thank you. But what do you mean by "kindly include this roughly every 15 lines."? I don't get you. 

This fix, or last commit from this PR 

for 3.15 version. If any planned for release, we need to add these changes there. So no impact in current dev version

**Pull request merged**
