### PR TITLE
3.15.0 release

### PR DESCRIPTION
**Pull request by dbeck121**
Final release version for 3.15.0 with devtoberfest promotion 

CleanShot 2024-09-08 at 14 34 55@2x

@fippu82 and @incpi please check and give your thumbs up!

### CODE REVIEW

**Comment by dbeck121** [comment]
@fippu82 and @incpi please have a look and check

**Review by incpi — APPROVED** [review]
One suggestion,

Post event if anyone installs, then popup should not be there.
It should have separate tab if you think that's needs it in 1st popup. 

Nothing else. Thank you.

**Comment by fippu82** [comment]
OK for me too as far as I can see. Popup looks good!

**Review by fippu82 — DISMISSED** [review]

**Comment by dbeck121** [comment]
I added a new figaf teaser and @incpi I added a new seperate tab. Good idea

**Comment by dbeck121** [comment]
> Post event if anyone installs, then popup should not be there.

@incpi what do you mean with that? So just when someone installs CPI Helper?

**Comment by incpi** [comment]
Hey @dbeck121 , 

We have 2 popups, regular and devfest, so post your event , on new install we should see only regular and devfest in tab. 

So they can still checkout but no additional  popups.

**Pull request merged**
